# Generated by Django 5.0.4 on 2024-04-26 21:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='events')),
                ('eventName', models.CharField(max_length=200)),
                ('generalInfo', models.TextField()),
                ('dateOfEvent', models.DateField()),
                ('eventClosingDate', models.DateField()),
                ('time', models.TimeField()),
                ('country', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('bankName', models.CharField(max_length=200)),
                ('accountNumber', models.CharField(max_length=30)),
                ('accountName', models.CharField(max_length=200)),
                ('socialMedia', models.URLField()),
                ('congratulatoryMessage', models.TextField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
