# Generated by Django 5.0.4 on 2024-04-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_alter_event_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
