# Generated by Django 5.0.4 on 2024-04-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0003_alter_event_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='congratulatoryMessage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
