# Generated by Django 5.0.4 on 2024-04-26 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0004_alter_event_congratulatorymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='username',
            field=models.CharField(default='will be gotten from request.user', max_length=200),
        ),
    ]
