[project]
name = "will-be-there-backend"
version = "0.1.0"
requires-python = ">=3.10"

[tool.ruff]
line-length = 210
target-version = "py310"

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
]
ignore = []

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
check_untyped_defs = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "backend.settings"

[[tool.mypy.overrides]]
module = "django.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["rest_framework.*", "drf_yasg.*", "fernet_fields.*", "celery.*", "environ.*", "stripe.*", "rest_framework_simplejwt.*", "django_filters.*", "corsheaders.*", "channels.*"]
ignore_missing_imports = true
