# Generated by Django 6.0.1 on 2026-01-16 13:51

from django.db import migrations, models

import Events.validators


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0008_remove_event_username_event_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.ImageField(upload_to="events", validators=[Events.validators.validate_image_file]),
        ),
    ]
