# Generated by Django 6.0.1 on 2026-01-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0009_alter_event_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="picture",
            field=models.ImageField(upload_to="events"),
        ),
    ]
