# Generated by Django 6.0.1 on 2026-01-27 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Events", "0010_alter_event_picture"),
    ]

    operations = [
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guestName", models.CharField(max_length=200)),
                ("guestEmail", models.EmailField(max_length=254)),
                ("isAttending", models.CharField(default="Yes", max_length=10)),
                ("isFriendsComing", models.CharField(default="No", max_length=10)),
                ("message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="Events.event",
                    ),
                ),
            ],
        ),
    ]
