# Generated by Django 6.0.1 on 2026-01-27 23:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0011_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="currency",
            field=models.CharField(default="GHS", max_length=10),
        ),
        migrations.AddField(
            model_name="event",
            name="inclusions",
            field=models.TextField(
                blank=True, help_text="What the cost covers", null=True
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="is_redeemable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="parent_rsvp",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plus_ones",
                to="Events.rsvp",
            ),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Refunded", "Refunded"),
                    ("N/A", "Not Applicable"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="rsvp",
            name="rsvp_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
