# Generated by Django 6.0.1 on 2026-02-03 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0013_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rsvp',
            name='payment_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled'), ('N/A', 'Not Applicable')], default='Pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('currency', models.CharField(default='GHS', max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Total number of tickets available for this type')),
                ('sold', models.PositiveIntegerField(default=0, help_text='Number of tickets sold')),
                ('sale_start_date', models.DateTimeField(blank=True, null=True)),
                ('sale_end_date', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='Events.event')),
            ],
        ),
        migrations.AddField(
            model_name='rsvp',
            name='ticket_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsvps', to='Events.tickettype'),
        ),
    ]
