# Generated by Django 6.0.1 on 2026-02-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0014_rsvp_stripe_payment_intent_alter_rsvp_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
