# Generated by Django 6.0.1 on 2026-02-04 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Events", "0015_rsvp_checkout_request_id_rsvp_mpesa_receipt_number"),
        ("Organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this event (for audit trail)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_events",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Organization that owns this event",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="Organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="DEPRECATED: Use organization instead",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_legacy",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
