# Generated by Django 5.0.4 on 2024-04-18 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0002_userprofile_validation_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='validation_code',
            new_name='verification_code',
        ),
    ]
