# Generated by Django 5.0.4 on 2024-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0003_rename_validation_code_userprofile_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_code',
            field=models.CharField(default='hftrg&dhdywezvxddjdd', max_length=50),
        ),
    ]
