# Generated by Django

from django.db import migrations
from django.utils.text import slugify


def migrate_user_events_to_organizations(apps, schema_editor):
    """
    Data migration: Create an Organization for each existing user
    and transfer their events to that organization.
    """
    User = apps.get_model('auth', 'User')
    Organization = apps.get_model('Organizations', 'Organization')
    OrganizationMember = apps.get_model('Organizations', 'OrganizationMember')
    Event = apps.get_model('Events', 'Event')

    for user in User.objects.all():
        # Create personal organization for each user
        base_slug = slugify(user.username)
        slug = base_slug
        counter = 1

        # Ensure unique slug
        while Organization.objects.filter(slug=slug).exists():
            slug = f"{base_slug}-{counter}"
            counter += 1

        org = Organization.objects.create(
            name=f"{user.username}'s Organization",
            slug=slug,
            owner=user,
            subscription_tier='free'
        )

        # Add user as owner member
        OrganizationMember.objects.create(
            organization=org,
            user=user,
            role='owner',
            is_active=True
        )

        # Transfer all events from this user to the new organization
        events_updated = Event.objects.filter(user=user, organization__isnull=True).update(
            organization=org,
            created_by=user
        )

        print(f"[OK] Created org '{org.name}' and migrated {events_updated} events for user '{user.username}'")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Clear organization references from events.
    Note: This does NOT delete organizations to prevent data loss.
    """
    Event = apps.get_model('Events', 'Event')
    Event.objects.all().update(organization=None, created_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0001_initial'),
        ('Events', '0016_event_created_by_event_organization_alter_event_user'),
    ]

    operations = [
        migrations.RunPython(
            migrate_user_events_to_organizations,
            reverse_migration
        ),
    ]
