# Generated by Django 5.0.7

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0006_userprofile_timestamps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="Timestamp when profile was created"),
        ),
    ]
