# Generated by Django 6.0.1 on 2026-01-18 14:26

import fernet_fields.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0007_alter_userprofile_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="phone_number",
            field=fernet_fields.fields.EncryptedCharField(max_length=200),
        ),
    ]
