# Generated by Django 6.0.1 on 2026-01-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("userProfile", "0008_alter_userprofile_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reset_password_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
